-- HealthWatch NG — seed data (GENERATED by `npm run ingest`; do not edit by hand)
-- Generated: 2026-08-04T19:29:23.067Z
-- Cholera source: WHO Global Cholera & AWD dashboard (HDX) (live fetch)
-- Provenance per table (real | modelled | synthetic):
--   state_risks: synthetic
--   outbreak_alerts: synthetic
--   weekly_case_trends: modelled
--   data_sources: real
--   audit_log: synthetic
--   forecast_points: modelled
--   high_risk_lgas: synthetic
--   epi_reports: real
-- Run AFTER schema.sql in the Supabase SQL editor.

insert into public.state_risks (id, name, code, risk, active_cases, dominant_disease) values
  ('AB', 'Abia', 'AB', 'Critical', 347, 'Malaria'),
  ('AD', 'Adamawa', 'AD', 'High', 180, 'Cerebrospinal Meningitis'),
  ('AK', 'Akwa Ibom', 'AK', 'Critical', 386, 'Lassa Fever'),
  ('AN', 'Anambra', 'AN', 'High', 316, 'Monkeypox'),
  ('BA', 'Bauchi', 'BA', 'High', 268, 'Malaria'),
  ('BY', 'Bayelsa', 'BY', 'High', 273, 'Cerebrospinal Meningitis'),
  ('BE', 'Benue', 'BE', 'High', 227, 'Monkeypox'),
  ('BO', 'Borno', 'BO', 'High', 215, 'Lassa Fever'),
  ('CR', 'Cross River', 'CR', 'Critical', 338, 'Monkeypox'),
  ('DE', 'Delta', 'DE', 'Medium', 144, 'Monkeypox'),
  ('EB', 'Ebonyi', 'EB', 'High', 213, 'Lassa Fever'),
  ('ED', 'Edo', 'ED', 'High', 189, 'Monkeypox'),
  ('EK', 'Ekiti', 'EK', 'High', 228, 'Lassa Fever'),
  ('EN', 'Enugu', 'EN', 'Critical', 339, 'Cerebrospinal Meningitis'),
  ('GO', 'Gombe', 'GO', 'Medium', 137, 'Cerebrospinal Meningitis'),
  ('IM', 'Imo', 'IM', 'High', 304, 'Cerebrospinal Meningitis'),
  ('JI', 'Jigawa', 'JI', 'Critical', 393, 'Monkeypox'),
  ('KD', 'Kaduna', 'KD', 'High', 206, 'Cholera'),
  ('KN', 'Kano', 'KN', 'Critical', 379, 'Monkeypox'),
  ('KT', 'Katsina', 'KT', 'Critical', 371, 'Cerebrospinal Meningitis'),
  ('KB', 'Kebbi', 'KB', 'Medium', 160, 'Cholera'),
  ('KO', 'Kogi', 'KO', 'High', 269, 'Cerebrospinal Meningitis'),
  ('KW', 'Kwara', 'KW', 'Critical', 326, 'Cerebrospinal Meningitis'),
  ('LA', 'Lagos', 'LA', 'High', 192, 'Monkeypox'),
  ('NA', 'Nasarawa', 'NA', 'Medium', 161, 'Cerebrospinal Meningitis'),
  ('NI', 'Niger', 'NI', 'High', 311, 'Cerebrospinal Meningitis'),
  ('OG', 'Ogun', 'OG', 'Critical', 387, 'Monkeypox'),
  ('ON', 'Ondo', 'ON', 'Medium', 177, 'Monkeypox'),
  ('OS', 'Osun', 'OS', 'Medium', 178, 'Malaria'),
  ('OY', 'Oyo', 'OY', 'Medium', 102, 'Malaria'),
  ('PL', 'Plateau', 'PL', 'Critical', 371, 'Cholera'),
  ('RI', 'Rivers', 'RI', 'Critical', 389, 'Lassa Fever'),
  ('SO', 'Sokoto', 'SO', 'Medium', 115, 'Cholera'),
  ('TA', 'Taraba', 'TA', 'Medium', 125, 'Malaria'),
  ('YO', 'Yobe', 'YO', 'Critical', 405, 'Lassa Fever'),
  ('ZA', 'Zamfara', 'ZA', 'Critical', 403, 'Malaria'),
  ('FCT', 'FCT', 'FCT', 'Medium', 126, 'Monkeypox')
on conflict (id) do nothing;

insert into public.outbreak_alerts (id, disease, lga, state, risk, case_count, triggered_at, status, description, reported_by, contacts_traced, fatalities, detection_time_hrs) values
  ('AL-2026-0140', 'Cholera', 'Maiduguri', 'Borno', 'Critical', 511, '2026-07-31T05:29:23.067Z', 'Investigating', 'Cholera cluster detected in Maiduguri LGA, Borno. Case-based surveillance triggered a signal above the epidemic threshold.', 'Dr. Ngozi Umeh', 361, 11, 50.9),
  ('AL-2026-0141', 'Cholera', 'Bade', 'Yobe', 'High', 342, '2026-07-25T12:29:23.067Z', 'Acknowledged', 'Cholera cluster detected in Bade LGA, Yobe. Case-based surveillance triggered a signal above the epidemic threshold.', 'Dr. Fatima Sani', 230, 16, 17.3),
  ('AL-2026-0142', 'Lassa Fever', 'Owo', 'Ondo', 'High', 88, '2026-07-17T17:29:23.067Z', 'Resolved', 'Lassa Fever cluster detected in Owo LGA, Ondo. Case-based surveillance triggered a signal above the epidemic threshold.', 'Dr. Fatima Sani', 130, 2, 42.5),
  ('AL-2026-0143', 'Lassa Fever', 'Etsako West', 'Edo', 'Critical', 132, '2026-07-30T12:29:23.067Z', 'Resolved', 'Lassa Fever cluster detected in Etsako West LGA, Edo. Case-based surveillance triggered a signal above the epidemic threshold.', 'Dr. Chukwu Eze', 96, 5, 61.1),
  ('AL-2026-0144', 'Cerebrospinal Meningitis', 'Gusau', 'Zamfara', 'Critical', 203, '2026-07-25T23:29:23.067Z', 'Investigating', 'Cerebrospinal Meningitis cluster detected in Gusau LGA, Zamfara. Case-based surveillance triggered a signal above the epidemic threshold.', 'Dr. Amina Bello', 189, 8, 38.6),
  ('AL-2026-0145', 'Cerebrospinal Meningitis', 'Sabon Gari', 'Kaduna', 'High', 156, '2026-07-17T20:29:23.067Z', 'Resolved', 'Cerebrospinal Meningitis cluster detected in Sabon Gari LGA, Kaduna. Case-based surveillance triggered a signal above the epidemic threshold.', 'Dr. Fatima Sani', 233, 2, 7.2),
  ('AL-2026-0146', 'Cholera', 'Ajingi', 'Kano', 'Medium', 97, '2026-08-02T10:29:23.067Z', 'Investigating', 'Cholera cluster detected in Ajingi LGA, Kano. Case-based surveillance triggered a signal above the epidemic threshold.', 'Dr. Amina Bello', 78, 3, 17.6),
  ('AL-2026-0147', 'Monkeypox', 'Eket', 'Akwa Ibom', 'Medium', 23, '2026-07-25T00:29:23.067Z', 'Resolved', 'Monkeypox cluster detected in Eket LGA, Akwa Ibom. Case-based surveillance triggered a signal above the epidemic threshold.', 'Dr. Ngozi Umeh', 26, 1, 22.6),
  ('AL-2026-0148', 'Cholera', 'Shomolu', 'Lagos', 'Medium', 64, '2026-07-18T20:29:23.067Z', 'Resolved', 'Cholera cluster detected in Shomolu LGA, Lagos. Case-based surveillance triggered a signal above the epidemic threshold.', 'Dr. Fatima Sani', 94, 2, 19.5),
  ('AL-2026-0149', 'Malaria', 'Jos North', 'Plateau', 'Medium', 418, '2026-08-04T04:29:23.067Z', 'Investigating', 'Malaria cluster detected in Jos North LGA, Plateau. Case-based surveillance triggered a signal above the epidemic threshold.', 'Dr. Tunde Okon', 611, 13, 62.4),
  ('AL-2026-0150', 'Cholera', 'Bama', 'Borno', 'High', 276, '2026-07-23T00:29:23.067Z', 'Acknowledged', 'Cholera cluster detected in Bama LGA, Borno. Case-based surveillance triggered a signal above the epidemic threshold.', 'Dr. Chukwu Eze', 301, 3, 60.7),
  ('AL-2026-0151', 'Lassa Fever', 'Jalingo', 'Taraba', 'Medium', 37, '2026-07-16T20:29:23.067Z', 'Investigating', 'Lassa Fever cluster detected in Jalingo LGA, Taraba. Case-based surveillance triggered a signal above the epidemic threshold.', 'Dr. Amina Bello', 39, 1, 6.5),
  ('AL-2026-0152', 'Monkeypox', 'Ikom', 'Cross River', 'Low', 12, '2026-07-30T05:29:23.067Z', 'Resolved', 'Monkeypox cluster detected in Ikom LGA, Cross River. Case-based surveillance triggered a signal above the epidemic threshold.', 'Dr. Tunde Okon', 9, 0, 31.4),
  ('AL-2026-0153', 'Cholera', 'Damaturu', 'Yobe', 'High', 189, '2026-07-28T06:29:23.067Z', 'Acknowledged', 'Cholera cluster detected in Damaturu LGA, Yobe. Case-based surveillance triggered a signal above the epidemic threshold.', 'Dr. Amina Bello', 208, 9, 69.3),
  ('AL-2026-0154', 'Lassa Fever', 'Ose', 'Ondo', 'Medium', 41, '2026-07-18T12:29:23.067Z', 'Resolved', 'Lassa Fever cluster detected in Ose LGA, Ondo. Case-based surveillance triggered a signal above the epidemic threshold.', 'Dr. Fatima Sani', 31, 2, 45.6)
on conflict (id) do nothing;

insert into public.weekly_case_trends (week, cholera, lassa_fever, meningitis) values
  ('W17', 3141, 999, 588),
  ('W18', 3186, 1023, 574),
  ('W19', 2727, 865, 503),
  ('W20', 2417, 780, 455),
  ('W21', 2439, 813, 450),
  ('W22', 2159, 701, 407),
  ('W23', 1551, 515, 293),
  ('W24', 1368, 461, 260),
  ('W25', 1038, 326, 208),
  ('W26', 703, 231, 144),
  ('W27', 922, 295, 195),
  ('W28', 554, 179, 97)
on conflict (week) do nothing;

insert into public.data_sources (id, name, description, status, last_sync, record_count) values
  ('DS-WHO', 'WHO Global Cholera & AWD (HDX)', 'WHO Global Cholera & AWD dashboard (HDX) · Nigeria 50,290 cases / 338 deaths (2025-12-29 → 2026-07-20).', 'Connected', '2026-08-04T19:29:23.067Z', 27),
  ('DS-IDSR', 'IDSR Weekly Reports (NCDC)', 'NCDC Integrated Disease Surveillance & Response — PDF only, not yet parsed.', 'Degraded', '2026-08-03T17:29:23.067Z', 0),
  ('DS-DHIS2', 'DHIS2 National Instance', 'Federal DHIS2 aggregate feed — connector not configured.', 'Offline', '2026-07-26T19:29:23.067Z', 0)
on conflict (id) do nothing;

insert into public.audit_log (id, user_name, action, resource, timestamp, category) values
  ('EV-30001', 'ingest-pipeline', 'Ingested WHO cholera snapshot — Nigeria 50,290 cases, ranked #2 of 27 countries', 'epi_reports, weekly_case_trends, forecast_points', '2026-08-04T19:29:23.067Z', 'Data'),
  ('EV-30002', 'Dr. Amina Bello', 'Signed in', 'auth/session', '2026-08-04T16:29:23.067Z', 'Auth'),
  ('EV-30003', 'Dr. Tunde Okon', 'Acknowledged alert AL-2026-0141', 'outbreak_alerts', '2026-08-04T10:29:23.067Z', 'Alert'),
  ('EV-30004', 'Dr. Ngozi Umeh', 'Exported weekly bulletin (PDF)', 'epi_reports', '2026-08-03T23:29:23.067Z', 'Export'),
  ('EV-30005', 'System Admin', 'Updated risk threshold config', 'config/thresholds', '2026-08-03T13:29:23.067Z', 'Config'),
  ('EV-30006', 'Dr. Fatima Sani', 'Signed in', 'auth/session', '2026-08-02T19:29:23.067Z', 'Auth'),
  ('EV-30007', 'ingest-pipeline', 'Refreshed state risk grid', 'state_risks', '2026-08-03T17:29:23.067Z', 'Data')
on conflict (id) do nothing;

insert into public.forecast_points (week, actual, predicted, lower, upper) values
  ('W21', 2439, 2269, 1912, 2626),
  ('W22', 2159, 2004, 1647, 2361),
  ('W23', 1551, 1739, 1382, 2096),
  ('W24', 1368, 1474, 1117, 1831),
  ('W25', 1038, 1209, 852, 1566),
  ('W26', 703, 944, 587, 1301),
  ('W27', 922, 679, 322, 1036),
  ('W28', 554, 415, 58, 772),
  ('W29', null, 150, 0, 596),
  ('W30', null, 0, 0, 536),
  ('W31', null, 0, 0, 625),
  ('W32', null, 0, 0, 714),
  ('W33', null, 0, 0, 803),
  ('W34', null, 0, 0, 893)
on conflict (week) do nothing;

insert into public.high_risk_lgas (id, lga, state, disease, predicted_cases, trend, change_pct) values
  ('LGA-001', 'Maiduguri', 'Borno', 'Cholera', 686, 'down', 19.3),
  ('LGA-002', 'Bade', 'Yobe', 'Cholera', 415, 'up', 19.3),
  ('LGA-003', 'Owo', 'Ondo', 'Lassa Fever', 98, 'down', 18.2),
  ('LGA-004', 'Etsako West', 'Edo', 'Lassa Fever', 200, 'up', 10.8),
  ('LGA-005', 'Gusau', 'Zamfara', 'Cerebrospinal Meningitis', 285, 'down', 10.5),
  ('LGA-006', 'Sabon Gari', 'Kaduna', 'Cerebrospinal Meningitis', 213, 'down', -19.2),
  ('LGA-007', 'Ajingi', 'Kano', 'Cholera', 158, 'up', 15.5)
on conflict (id) do nothing;

insert into public.epi_reports (epi_week, period_label, total_cases_reported, new_outbreaks, under_investigation, states_reporting, recovery_rate, case_fatality_rate) values
  ('Epi Week 31', 'Week 31, 2026 · cumulative', 50290, 5, 5, 37, 93.3, 0.7),
  ('Epi Week 30', 'Week 30, 2026 · cumulative', 47273, 5, 5, 37, 93.3, 0.7)
on conflict (epi_week) do nothing;

-- ---------------------------------------------------------------------------
-- OPTIONAL demo accounts (so the Admin → Users tab isn't empty).
-- profiles.id is a FK to auth.users, so profiles can't be seeded directly;
-- instead we insert auth.users and let the handle_new_user() trigger create
-- the matching profiles rows from raw_user_meta_data.
-- Each account's password is 'HealthWatch#2026'.
-- This block is version-sensitive (GoTrue internals). If it errors on your
-- Supabase version, DELETE it and just self-register on the signup page —
-- everything above this line seeds fine on its own.
-- ---------------------------------------------------------------------------
insert into auth.users
  (instance_id, id, aud, role, email, encrypted_password, email_confirmed_at,
   raw_app_meta_data, raw_user_meta_data, created_at, updated_at,
   confirmation_token, recovery_token, email_change_token_new, email_change)
values
  ('00000000-0000-0000-0000-000000000000', gen_random_uuid(), 'authenticated', 'authenticated',
   'amina.bello@ncdc.demo', crypt('HealthWatch#2026', gen_salt('bf')), now(),
   '{"provider":"email","providers":["email"]}',
   '{"name":"Dr. Amina Bello","role":"State Coordinator","state":"Borno","phone":"08030000001"}',
   now(), now(), '', '', '', ''),
  ('00000000-0000-0000-0000-000000000000', gen_random_uuid(), 'authenticated', 'authenticated',
   'tunde.okon@ncdc.demo', crypt('HealthWatch#2026', gen_salt('bf')), now(),
   '{"provider":"email","providers":["email"]}',
   '{"name":"Dr. Tunde Okon","role":"Health Officer","state":"Lagos","phone":"08030000002"}',
   now(), now(), '', '', '', ''),
  ('00000000-0000-0000-0000-000000000000', gen_random_uuid(), 'authenticated', 'authenticated',
   'fatima.sani@ncdc.demo', crypt('HealthWatch#2026', gen_salt('bf')), now(),
   '{"provider":"email","providers":["email"]}',
   '{"name":"Dr. Fatima Sani","role":"Data Scientist","state":"Kano","phone":"08030000003"}',
   now(), now(), '', '', '', ''),
  ('00000000-0000-0000-0000-000000000000', gen_random_uuid(), 'authenticated', 'authenticated',
   'admin@ncdc.demo', crypt('HealthWatch#2026', gen_salt('bf')), now(),
   '{"provider":"email","providers":["email"]}',
   '{"name":"System Admin","role":"System Admin","state":"FCT","phone":"08030000004"}',
   now(), now(), '', '', '', '')
on conflict (id) do nothing;
