-- HealthWatch NG — seed data (GENERATED by `npm run ingest`; do not edit by hand)
-- Generated: 2026-07-30T00:36:03.377Z
-- Cholera source: WHO Global Cholera & AWD dashboard (HDX) (live fetch)
-- Provenance per table (real | modelled | synthetic):
--   state_risks: synthetic
--   outbreak_alerts: synthetic
--   weekly_case_trends: modelled
--   data_sources: real
--   audit_log: synthetic
--   forecast_points: modelled
--   high_risk_lgas: synthetic
--   epi_reports: real
-- Run AFTER schema.sql in the Supabase SQL editor.

insert into public.state_risks (id, name, code, risk, active_cases, dominant_disease) values
  ('AB', 'Abia', 'AB', 'Medium', 108, 'Malaria'),
  ('AD', 'Adamawa', 'AD', 'Low', 56, 'Cerebrospinal Meningitis'),
  ('AK', 'Akwa Ibom', 'AK', 'Medium', 120, 'Lassa Fever'),
  ('AN', 'Anambra', 'AN', 'Medium', 98, 'Monkeypox'),
  ('BA', 'Bauchi', 'BA', 'Medium', 83, 'Malaria'),
  ('BY', 'Bayelsa', 'BY', 'Medium', 85, 'Cerebrospinal Meningitis'),
  ('BE', 'Benue', 'BE', 'Medium', 71, 'Monkeypox'),
  ('BO', 'Borno', 'BO', 'Low', 67, 'Lassa Fever'),
  ('CR', 'Cross River', 'CR', 'Medium', 105, 'Monkeypox'),
  ('DE', 'Delta', 'DE', 'Low', 45, 'Monkeypox'),
  ('EB', 'Ebonyi', 'EB', 'Low', 66, 'Lassa Fever'),
  ('ED', 'Edo', 'ED', 'Low', 59, 'Monkeypox'),
  ('EK', 'Ekiti', 'EK', 'Medium', 71, 'Lassa Fever'),
  ('EN', 'Enugu', 'EN', 'Medium', 105, 'Cerebrospinal Meningitis'),
  ('GO', 'Gombe', 'GO', 'Low', 43, 'Cerebrospinal Meningitis'),
  ('IM', 'Imo', 'IM', 'Medium', 95, 'Cerebrospinal Meningitis'),
  ('JI', 'Jigawa', 'JI', 'Medium', 122, 'Monkeypox'),
  ('KD', 'Kaduna', 'KD', 'Low', 64, 'Cholera'),
  ('KN', 'Kano', 'KN', 'Medium', 118, 'Monkeypox'),
  ('KT', 'Katsina', 'KT', 'Medium', 115, 'Cerebrospinal Meningitis'),
  ('KB', 'Kebbi', 'KB', 'Low', 50, 'Cholera'),
  ('KO', 'Kogi', 'KO', 'Medium', 84, 'Cerebrospinal Meningitis'),
  ('KW', 'Kwara', 'KW', 'Medium', 101, 'Cerebrospinal Meningitis'),
  ('LA', 'Lagos', 'LA', 'Low', 60, 'Monkeypox'),
  ('NA', 'Nasarawa', 'NA', 'Low', 50, 'Cerebrospinal Meningitis'),
  ('NI', 'Niger', 'NI', 'Medium', 97, 'Cerebrospinal Meningitis'),
  ('OG', 'Ogun', 'OG', 'Medium', 120, 'Monkeypox'),
  ('ON', 'Ondo', 'ON', 'Low', 55, 'Monkeypox'),
  ('OS', 'Osun', 'OS', 'Low', 55, 'Malaria'),
  ('OY', 'Oyo', 'OY', 'Low', 32, 'Malaria'),
  ('PL', 'Plateau', 'PL', 'Medium', 115, 'Cholera'),
  ('RI', 'Rivers', 'RI', 'Medium', 121, 'Lassa Fever'),
  ('SO', 'Sokoto', 'SO', 'Low', 36, 'Cholera'),
  ('TA', 'Taraba', 'TA', 'Low', 39, 'Malaria'),
  ('YO', 'Yobe', 'YO', 'Medium', 126, 'Lassa Fever'),
  ('ZA', 'Zamfara', 'ZA', 'Medium', 125, 'Malaria'),
  ('FCT', 'FCT', 'FCT', 'Low', 39, 'Monkeypox')
on conflict (id) do nothing;

insert into public.outbreak_alerts (id, disease, lga, state, risk, case_count, triggered_at, status, description, reported_by, contacts_traced, fatalities, detection_time_hrs) values
  ('AL-2026-0140', 'Cholera', 'Maiduguri', 'Borno', 'Critical', 511, '2026-07-25T10:36:03.377Z', 'Investigating', 'Cholera cluster detected in Maiduguri LGA, Borno. Case-based surveillance triggered a signal above the epidemic threshold.', 'Dr. Ngozi Umeh', 361, 11, 50.9),
  ('AL-2026-0141', 'Cholera', 'Bade', 'Yobe', 'High', 342, '2026-07-19T17:36:03.377Z', 'Acknowledged', 'Cholera cluster detected in Bade LGA, Yobe. Case-based surveillance triggered a signal above the epidemic threshold.', 'Dr. Fatima Sani', 230, 16, 17.3),
  ('AL-2026-0142', 'Lassa Fever', 'Owo', 'Ondo', 'High', 88, '2026-07-11T22:36:03.377Z', 'Resolved', 'Lassa Fever cluster detected in Owo LGA, Ondo. Case-based surveillance triggered a signal above the epidemic threshold.', 'Dr. Fatima Sani', 130, 2, 42.5),
  ('AL-2026-0143', 'Lassa Fever', 'Etsako West', 'Edo', 'Critical', 132, '2026-07-24T17:36:03.377Z', 'Resolved', 'Lassa Fever cluster detected in Etsako West LGA, Edo. Case-based surveillance triggered a signal above the epidemic threshold.', 'Dr. Chukwu Eze', 96, 5, 61.1),
  ('AL-2026-0144', 'Cerebrospinal Meningitis', 'Gusau', 'Zamfara', 'Critical', 203, '2026-07-20T04:36:03.377Z', 'Investigating', 'Cerebrospinal Meningitis cluster detected in Gusau LGA, Zamfara. Case-based surveillance triggered a signal above the epidemic threshold.', 'Dr. Amina Bello', 189, 8, 38.6),
  ('AL-2026-0145', 'Cerebrospinal Meningitis', 'Sabon Gari', 'Kaduna', 'High', 156, '2026-07-12T01:36:03.377Z', 'Resolved', 'Cerebrospinal Meningitis cluster detected in Sabon Gari LGA, Kaduna. Case-based surveillance triggered a signal above the epidemic threshold.', 'Dr. Fatima Sani', 233, 2, 7.2),
  ('AL-2026-0146', 'Cholera', 'Ajingi', 'Kano', 'Medium', 97, '2026-07-27T15:36:03.377Z', 'Investigating', 'Cholera cluster detected in Ajingi LGA, Kano. Case-based surveillance triggered a signal above the epidemic threshold.', 'Dr. Amina Bello', 78, 3, 17.6),
  ('AL-2026-0147', 'Monkeypox', 'Eket', 'Akwa Ibom', 'Medium', 23, '2026-07-19T05:36:03.377Z', 'Resolved', 'Monkeypox cluster detected in Eket LGA, Akwa Ibom. Case-based surveillance triggered a signal above the epidemic threshold.', 'Dr. Ngozi Umeh', 26, 1, 22.6),
  ('AL-2026-0148', 'Cholera', 'Shomolu', 'Lagos', 'Medium', 64, '2026-07-13T01:36:03.377Z', 'Resolved', 'Cholera cluster detected in Shomolu LGA, Lagos. Case-based surveillance triggered a signal above the epidemic threshold.', 'Dr. Fatima Sani', 94, 2, 19.5),
  ('AL-2026-0149', 'Malaria', 'Jos North', 'Plateau', 'Medium', 418, '2026-07-29T09:36:03.377Z', 'Investigating', 'Malaria cluster detected in Jos North LGA, Plateau. Case-based surveillance triggered a signal above the epidemic threshold.', 'Dr. Tunde Okon', 611, 13, 62.4),
  ('AL-2026-0150', 'Cholera', 'Bama', 'Borno', 'High', 276, '2026-07-17T05:36:03.377Z', 'Acknowledged', 'Cholera cluster detected in Bama LGA, Borno. Case-based surveillance triggered a signal above the epidemic threshold.', 'Dr. Chukwu Eze', 301, 3, 60.7),
  ('AL-2026-0151', 'Lassa Fever', 'Jalingo', 'Taraba', 'Medium', 37, '2026-07-11T01:36:03.377Z', 'Investigating', 'Lassa Fever cluster detected in Jalingo LGA, Taraba. Case-based surveillance triggered a signal above the epidemic threshold.', 'Dr. Amina Bello', 39, 1, 6.5),
  ('AL-2026-0152', 'Monkeypox', 'Ikom', 'Cross River', 'Low', 12, '2026-07-24T10:36:03.377Z', 'Resolved', 'Monkeypox cluster detected in Ikom LGA, Cross River. Case-based surveillance triggered a signal above the epidemic threshold.', 'Dr. Tunde Okon', 9, 0, 31.4),
  ('AL-2026-0153', 'Cholera', 'Damaturu', 'Yobe', 'High', 189, '2026-07-22T11:36:03.377Z', 'Acknowledged', 'Cholera cluster detected in Damaturu LGA, Yobe. Case-based surveillance triggered a signal above the epidemic threshold.', 'Dr. Amina Bello', 208, 9, 69.3),
  ('AL-2026-0154', 'Lassa Fever', 'Ose', 'Ondo', 'Medium', 41, '2026-07-12T17:36:03.377Z', 'Resolved', 'Lassa Fever cluster detected in Ose LGA, Ondo. Case-based surveillance triggered a signal above the epidemic threshold.', 'Dr. Fatima Sani', 31, 2, 45.6)
on conflict (id) do nothing;

insert into public.weekly_case_trends (week, cholera, lassa_fever, meningitis) values
  ('W12', 876, 274, 181),
  ('W13', 783, 254, 142),
  ('W14', 815, 253, 159),
  ('W15', 745, 245, 154),
  ('W16', 721, 264, 141),
  ('W17', 569, 192, 120),
  ('W18', 463, 167, 97),
  ('W19', 453, 168, 96),
  ('W20', 375, 114, 89),
  ('W21', 224, 78, 57),
  ('W22', 198, 63, 65),
  ('W23', 146, 49, 23)
on conflict (week) do nothing;

insert into public.data_sources (id, name, description, status, last_sync, record_count) values
  ('DS-WHO', 'WHO Global Cholera & AWD (HDX)', 'WHO Global Cholera & AWD dashboard (HDX) · Nigeria 11,723 cases / 117 deaths (2025-12-29 → 2026-06-08).', 'Connected', '2026-07-30T00:36:03.377Z', 24),
  ('DS-IDSR', 'IDSR Weekly Reports (NCDC)', 'NCDC Integrated Disease Surveillance & Response — PDF only, not yet parsed.', 'Degraded', '2026-07-28T22:36:03.377Z', 0),
  ('DS-DHIS2', 'DHIS2 National Instance', 'Federal DHIS2 aggregate feed — connector not configured.', 'Offline', '2026-07-21T00:36:03.377Z', 0)
on conflict (id) do nothing;

insert into public.audit_log (id, user_name, action, resource, timestamp, category) values
  ('EV-30001', 'ingest-pipeline', 'Ingested WHO cholera snapshot — Nigeria 11,723 cases, ranked #3 of 24 countries', 'epi_reports, weekly_case_trends, forecast_points', '2026-07-30T00:36:03.377Z', 'Data'),
  ('EV-30002', 'Dr. Amina Bello', 'Signed in', 'auth/session', '2026-07-29T21:36:03.377Z', 'Auth'),
  ('EV-30003', 'Dr. Tunde Okon', 'Acknowledged alert AL-2026-0141', 'outbreak_alerts', '2026-07-29T15:36:03.377Z', 'Alert'),
  ('EV-30004', 'Dr. Ngozi Umeh', 'Exported weekly bulletin (PDF)', 'epi_reports', '2026-07-29T04:36:03.377Z', 'Export'),
  ('EV-30005', 'Admin', 'Updated risk threshold config', 'config/thresholds', '2026-07-28T18:36:03.377Z', 'Config'),
  ('EV-30006', 'Dr. Fatima Sani', 'Signed in', 'auth/session', '2026-07-28T00:36:03.377Z', 'Auth'),
  ('EV-30007', 'ingest-pipeline', 'Refreshed state risk grid', 'state_risks', '2026-07-28T22:36:03.377Z', 'Data')
on conflict (id) do nothing;

insert into public.forecast_points (week, actual, predicted, lower, upper) values
  ('W16', 721, 672, 604, 740),
  ('W17', 569, 592, 524, 660),
  ('W18', 463, 513, 445, 581),
  ('W19', 453, 433, 365, 501),
  ('W20', 375, 354, 286, 422),
  ('W21', 224, 274, 206, 342),
  ('W22', 198, 195, 127, 263),
  ('W23', 146, 116, 48, 184),
  ('W24', null, 36, 0, 122),
  ('W25', null, 0, 0, 103),
  ('W26', null, 0, 0, 120),
  ('W27', null, 0, 0, 137),
  ('W28', null, 0, 0, 154),
  ('W29', null, 0, 0, 171)
on conflict (week) do nothing;

insert into public.high_risk_lgas (id, lga, state, disease, predicted_cases, trend, change_pct) values
  ('LGA-001', 'Maiduguri', 'Borno', 'Cholera', 686, 'down', 19.3),
  ('LGA-002', 'Bade', 'Yobe', 'Cholera', 415, 'up', 19.3),
  ('LGA-003', 'Owo', 'Ondo', 'Lassa Fever', 98, 'down', 18.2),
  ('LGA-004', 'Etsako West', 'Edo', 'Lassa Fever', 200, 'up', 10.8),
  ('LGA-005', 'Gusau', 'Zamfara', 'Cerebrospinal Meningitis', 285, 'down', 10.5),
  ('LGA-006', 'Sabon Gari', 'Kaduna', 'Cerebrospinal Meningitis', 213, 'down', -19.2),
  ('LGA-007', 'Ajingi', 'Kano', 'Cholera', 158, 'up', 15.5)
on conflict (id) do nothing;

insert into public.epi_reports (epi_week, period_label, total_cases_reported, new_outbreaks, under_investigation, states_reporting, recovery_rate, case_fatality_rate) values
  ('Epi Week 30', 'Week 30, 2026 · cumulative', 11723, 5, 5, 37, 93, 1),
  ('Epi Week 29', 'Week 29, 2026 · cumulative', 11020, 5, 5, 37, 93, 1)
on conflict (epi_week) do nothing;

-- ---------------------------------------------------------------------------
-- No accounts are seeded here. Create the single Admin account by running
-- supabase/seed_admin.sql in the SQL editor — the admin is provisioned by
-- SQL only, never through the UI.
-- ---------------------------------------------------------------------------
