// Module: Ingestion Pipeline — seed.sql Writer | Owner: Data Engineer
// Serialises the transformed dataset into supabase/seed.sql — a committed,
// network-free fallback that reproduces the same rows the loader upserts.
// Run it in the Supabase SQL editor after schema.sql when you don't want to
// run the pipeline. Includes an optional, clearly-marked demo-users block.

import { writeFileSync } from "node:fs";
import { join } from "node:path";
import type { Dataset, Provenance } from "./types";

type Cell = string | number | null;

function sqlVal(v: Cell): string {
  if (v === null) return "null";
  if (typeof v === "number") return String(v);
  return `'${v.replace(/'/g, "''")}'`;
}

function insertBlock(
  table: string,
  rows: Record<string, Cell>[],
  pk: string,
): string {
  if (rows.length === 0) return `-- ${table}: no rows\n`;
  const cols = Object.keys(rows[0]);
  const values = rows
    .map((r) => `  (${cols.map((c) => sqlVal(r[c])).join(", ")})`)
    .join(",\n");
  return (
    `insert into public.${table} (${cols.join(", ")}) values\n` +
    `${values}\n` +
    `on conflict (${pk}) do nothing;\n`
  );
}

const PK: Record<keyof Dataset, string> = {
  state_risks: "id",
  outbreak_alerts: "id",
  weekly_case_trends: "week",
  data_sources: "id",
  audit_log: "id",
  forecast_points: "week",
  high_risk_lgas: "id",
  epi_reports: "epi_week",
};

const DEMO_USERS_BLOCK = `
-- ---------------------------------------------------------------------------
-- OPTIONAL demo accounts (so the Admin → Users tab isn't empty).
-- profiles.id is a FK to auth.users, so profiles can't be seeded directly;
-- instead we insert auth.users and let the handle_new_user() trigger create
-- the matching profiles rows from raw_user_meta_data.
-- Each account's password is 'HealthWatch#2026'.
-- This block is version-sensitive (GoTrue internals). If it errors on your
-- Supabase version, DELETE it and just self-register on the signup page —
-- everything above this line seeds fine on its own.
-- ---------------------------------------------------------------------------
insert into auth.users
  (instance_id, id, aud, role, email, encrypted_password, email_confirmed_at,
   raw_app_meta_data, raw_user_meta_data, created_at, updated_at,
   confirmation_token, recovery_token, email_change_token_new, email_change)
values
  ('00000000-0000-0000-0000-000000000000', gen_random_uuid(), 'authenticated', 'authenticated',
   'amina.bello@ncdc.demo', crypt('HealthWatch#2026', gen_salt('bf')), now(),
   '{"provider":"email","providers":["email"]}',
   '{"name":"Dr. Amina Bello","role":"State Coordinator","state":"Borno","phone":"08030000001"}',
   now(), now(), '', '', '', ''),
  ('00000000-0000-0000-0000-000000000000', gen_random_uuid(), 'authenticated', 'authenticated',
   'tunde.okon@ncdc.demo', crypt('HealthWatch#2026', gen_salt('bf')), now(),
   '{"provider":"email","providers":["email"]}',
   '{"name":"Dr. Tunde Okon","role":"Health Officer","state":"Lagos","phone":"08030000002"}',
   now(), now(), '', '', '', ''),
  ('00000000-0000-0000-0000-000000000000', gen_random_uuid(), 'authenticated', 'authenticated',
   'fatima.sani@ncdc.demo', crypt('HealthWatch#2026', gen_salt('bf')), now(),
   '{"provider":"email","providers":["email"]}',
   '{"name":"Dr. Fatima Sani","role":"Data Scientist","state":"Kano","phone":"08030000003"}',
   now(), now(), '', '', '', ''),
  ('00000000-0000-0000-0000-000000000000', gen_random_uuid(), 'authenticated', 'authenticated',
   'admin@ncdc.demo', crypt('HealthWatch#2026', gen_salt('bf')), now(),
   '{"provider":"email","providers":["email"]}',
   '{"name":"System Admin","role":"System Admin","state":"FCT","phone":"08030000004"}',
   now(), now(), '', '', '', '')
on conflict (id) do nothing;
`;

export function writeSeedSql(
  dataset: Dataset,
  provenance: Record<keyof Dataset, Provenance>,
  meta: { source: string; live: boolean; generatedAt: string },
): string {
  const header =
    `-- HealthWatch NG — seed data (GENERATED by \`npm run ingest\`; do not edit by hand)\n` +
    `-- Generated: ${meta.generatedAt}\n` +
    `-- Cholera source: ${meta.source} (${meta.live ? "live fetch" : "offline baseline — illustrative"})\n` +
    `-- Provenance per table (real | modelled | synthetic):\n` +
    (Object.keys(dataset) as (keyof Dataset)[])
      .map((t) => `--   ${t}: ${provenance[t]}`)
      .join("\n") +
    `\n-- Run AFTER schema.sql in the Supabase SQL editor.\n\n`;

  const body = (Object.keys(dataset) as (keyof Dataset)[])
    .map((t) =>
      insertBlock(t, dataset[t] as unknown as Record<string, Cell>[], PK[t]),
    )
    .join("\n");

  const sql = header + body + DEMO_USERS_BLOCK;
  const outPath = join(process.cwd(), "supabase", "seed.sql");
  writeFileSync(outPath, sql, "utf8");
  return outPath;
}
