// Module: Ingestion Pipeline — seed.sql Writer | Owner: Data Engineer
// Serialises the transformed dataset into supabase/seed.sql — a committed,
// network-free fallback that reproduces the same rows the loader upserts.
// Run it in the Supabase SQL editor after schema.sql when you don't want to
// run the pipeline. Includes an optional, clearly-marked demo-users block.

import { writeFileSync } from "node:fs";
import { join } from "node:path";
import type { Dataset, Provenance } from "./types";

type Cell = string | number | null;

function sqlVal(v: Cell): string {
  if (v === null) return "null";
  if (typeof v === "number") return String(v);
  return `'${v.replace(/'/g, "''")}'`;
}

function insertBlock(
  table: string,
  rows: Record<string, Cell>[],
  pk: string,
): string {
  if (rows.length === 0) return `-- ${table}: no rows\n`;
  const cols = Object.keys(rows[0]);
  const values = rows
    .map((r) => `  (${cols.map((c) => sqlVal(r[c])).join(", ")})`)
    .join(",\n");
  return (
    `insert into public.${table} (${cols.join(", ")}) values\n` +
    `${values}\n` +
    `on conflict (${pk}) do nothing;\n`
  );
}

const PK: Record<keyof Dataset, string> = {
  state_risks: "id",
  outbreak_alerts: "id",
  weekly_case_trends: "week",
  data_sources: "id",
  audit_log: "id",
  forecast_points: "week",
  high_risk_lgas: "id",
  epi_reports: "epi_week",
};

const ADMIN_NOTE = `
-- ---------------------------------------------------------------------------
-- No accounts are seeded. Register on /signup, then promote your first
-- Super Admin by running supabase/promote_admin.sql in the SQL editor —
-- admin accounts are provisioned by SQL only, never through the UI.
-- ---------------------------------------------------------------------------
`;

export function writeSeedSql(
  dataset: Dataset,
  provenance: Record<keyof Dataset, Provenance>,
  meta: { source: string; live: boolean; generatedAt: string },
): string {
  const header =
    `-- HealthWatch NG — seed data (GENERATED by \`npm run ingest\`; do not edit by hand)\n` +
    `-- Generated: ${meta.generatedAt}\n` +
    `-- Cholera source: ${meta.source} (${meta.live ? "live fetch" : "offline baseline — illustrative"})\n` +
    `-- Provenance per table (real | modelled | synthetic):\n` +
    (Object.keys(dataset) as (keyof Dataset)[])
      .map((t) => `--   ${t}: ${provenance[t]}`)
      .join("\n") +
    `\n-- Run AFTER schema.sql in the Supabase SQL editor.\n\n`;

  const body = (Object.keys(dataset) as (keyof Dataset)[])
    .map((t) =>
      insertBlock(t, dataset[t] as unknown as Record<string, Cell>[], PK[t]),
    )
    .join("\n");

  const sql = header + body + ADMIN_NOTE;
  const outPath = join(process.cwd(), "supabase", "seed.sql");
  writeFileSync(outPath, sql, "utf8");
  return outPath;
}
